// Generated by the protocol buffer compiler. DO NOT EDIT!
// source: resources/protobuf/call.proto

package com.pbuf;

public final class Call {
	private Call() {
	}
	
	public static void registerAllExtensions(
			com.google.protobuf.ExtensionRegistry registry) {
	}
	
	public interface FunctionMessageOrBuilder extends
			com.google.protobuf.MessageOrBuilder {
		
		// required int32 function_id = 1;
		boolean hasFunctionId();
		
		int getFunctionId();
		
		// repeated .VariantMessage parameters = 2;
		java.util.List<com.pbuf.Call.VariantMessage> getParametersList();
		
		com.pbuf.Call.VariantMessage getParameters(int index);
		
		int getParametersCount();
		
		java.util.List<? extends com.pbuf.Call.VariantMessageOrBuilder>
				getParametersOrBuilderList();
		
		com.pbuf.Call.VariantMessageOrBuilder getParametersOrBuilder(int index);
	}
	
	public static final class FunctionMessage extends
			com.google.protobuf.GeneratedMessage implements
			FunctionMessageOrBuilder {
		// Use FunctionMessage.newBuilder() to construct.
		private FunctionMessage(Builder builder) {
			super(builder);
		}
		
		private FunctionMessage(boolean noInit) {
		}
		
		private static final FunctionMessage defaultInstance;
		
		public static FunctionMessage getDefaultInstance() {
			return defaultInstance;
		}
		
		public FunctionMessage getDefaultInstanceForType() {
			return defaultInstance;
		}
		
		public static final com.google.protobuf.Descriptors.Descriptor
				getDescriptor() {
			return com.pbuf.Call.internal_static_FunctionMessage_descriptor;
		}
		
		protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
				internalGetFieldAccessorTable() {
			return com.pbuf.Call.internal_static_FunctionMessage_fieldAccessorTable;
		}
		
		private int bitField0_;
		// required int32 function_id = 1;
		public static final int FUNCTION_ID_FIELD_NUMBER = 1;
		private int functionId_;
		
		public boolean hasFunctionId() {
			return ((bitField0_ & 0x00000001) == 0x00000001);
		}
		
		public int getFunctionId() {
			return functionId_;
		}
		
		// repeated .VariantMessage parameters = 2;
		public static final int PARAMETERS_FIELD_NUMBER = 2;
		private java.util.List<com.pbuf.Call.VariantMessage> parameters_;
		
		public java.util.List<com.pbuf.Call.VariantMessage> getParametersList() {
			return parameters_;
		}
		
		public java.util.List<? extends com.pbuf.Call.VariantMessageOrBuilder>
				getParametersOrBuilderList() {
			return parameters_;
		}
		
		public int getParametersCount() {
			return parameters_.size();
		}
		
		public com.pbuf.Call.VariantMessage getParameters(int index) {
			return parameters_.get(index);
		}
		
		public com.pbuf.Call.VariantMessageOrBuilder getParametersOrBuilder(
				int index) {
			return parameters_.get(index);
		}
		
		private void initFields() {
			functionId_ = 0;
			parameters_ = java.util.Collections.emptyList();
		}
		
		private byte memoizedIsInitialized = -1;
		
		public final boolean isInitialized() {
			byte isInitialized = memoizedIsInitialized;
			if (isInitialized != -1)
				return isInitialized == 1;
			
			if (!hasFunctionId()) {
				memoizedIsInitialized = 0;
				return false;
			}
			for (int i = 0; i < getParametersCount(); i++) {
				if (!getParameters(i).isInitialized()) {
					memoizedIsInitialized = 0;
					return false;
				}
			}
			memoizedIsInitialized = 1;
			return true;
		}
		
		public void writeTo(com.google.protobuf.CodedOutputStream output)
				throws java.io.IOException {
			getSerializedSize();
			if (((bitField0_ & 0x00000001) == 0x00000001)) {
				output.writeInt32(1, functionId_);
			}
			for (int i = 0; i < parameters_.size(); i++) {
				output.writeMessage(2, parameters_.get(i));
			}
			getUnknownFields().writeTo(output);
		}
		
		private int memoizedSerializedSize = -1;
		
		public int getSerializedSize() {
			int size = memoizedSerializedSize;
			if (size != -1)
				return size;
			
			size = 0;
			if (((bitField0_ & 0x00000001) == 0x00000001)) {
				size +=
						com.google.protobuf.CodedOutputStream.computeInt32Size(
								1, functionId_);
			}
			for (int i = 0; i < parameters_.size(); i++) {
				size +=
						com.google.protobuf.CodedOutputStream
								.computeMessageSize(2, parameters_.get(i));
			}
			size += getUnknownFields().getSerializedSize();
			memoizedSerializedSize = size;
			return size;
		}
		
		@java.lang.Override
		protected Object writeReplace() throws java.io.ObjectStreamException {
			return super.writeReplace();
		}
		
		public static com.pbuf.Call.FunctionMessage parseFrom(
				com.google.protobuf.ByteString data)
				throws com.google.protobuf.InvalidProtocolBufferException {
			return newBuilder().mergeFrom(data).buildParsed();
		}
		
		public static com.pbuf.Call.FunctionMessage parseFrom(
				com.google.protobuf.ByteString data,
				com.google.protobuf.ExtensionRegistryLite extensionRegistry)
				throws com.google.protobuf.InvalidProtocolBufferException {
			return newBuilder().mergeFrom(data, extensionRegistry)
					.buildParsed();
		}
		
		public static com.pbuf.Call.FunctionMessage parseFrom(byte[] data)
				throws com.google.protobuf.InvalidProtocolBufferException {
			return newBuilder().mergeFrom(data).buildParsed();
		}
		
		public static com.pbuf.Call.FunctionMessage parseFrom(byte[] data,
				com.google.protobuf.ExtensionRegistryLite extensionRegistry)
				throws com.google.protobuf.InvalidProtocolBufferException {
			return newBuilder().mergeFrom(data, extensionRegistry)
					.buildParsed();
		}
		
		public static com.pbuf.Call.FunctionMessage parseFrom(
				java.io.InputStream input) throws java.io.IOException {
			return newBuilder().mergeFrom(input).buildParsed();
		}
		
		public static com.pbuf.Call.FunctionMessage parseFrom(
				java.io.InputStream input,
				com.google.protobuf.ExtensionRegistryLite extensionRegistry)
				throws java.io.IOException {
			return newBuilder().mergeFrom(input, extensionRegistry)
					.buildParsed();
		}
		
		public static com.pbuf.Call.FunctionMessage parseDelimitedFrom(
				java.io.InputStream input) throws java.io.IOException {
			Builder builder = newBuilder();
			if (builder.mergeDelimitedFrom(input)) {
				return builder.buildParsed();
			} else {
				return null;
			}
		}
		
		public static com.pbuf.Call.FunctionMessage parseDelimitedFrom(
				java.io.InputStream input,
				com.google.protobuf.ExtensionRegistryLite extensionRegistry)
				throws java.io.IOException {
			Builder builder = newBuilder();
			if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
				return builder.buildParsed();
			} else {
				return null;
			}
		}
		
		public static com.pbuf.Call.FunctionMessage parseFrom(
				com.google.protobuf.CodedInputStream input)
				throws java.io.IOException {
			return newBuilder().mergeFrom(input).buildParsed();
		}
		
		public static com.pbuf.Call.FunctionMessage parseFrom(
				com.google.protobuf.CodedInputStream input,
				com.google.protobuf.ExtensionRegistryLite extensionRegistry)
				throws java.io.IOException {
			return newBuilder().mergeFrom(input, extensionRegistry)
					.buildParsed();
		}
		
		public static Builder newBuilder() {
			return Builder.create();
		}
		
		public Builder newBuilderForType() {
			return newBuilder();
		}
		
		public static Builder
				newBuilder(com.pbuf.Call.FunctionMessage prototype) {
			return newBuilder().mergeFrom(prototype);
		}
		
		public Builder toBuilder() {
			return newBuilder(this);
		}
		
		@java.lang.Override
		protected Builder newBuilderForType(
				com.google.protobuf.GeneratedMessage.BuilderParent parent) {
			Builder builder = new Builder(parent);
			return builder;
		}
		
		public static final class Builder extends
				com.google.protobuf.GeneratedMessage.Builder<Builder> implements
				com.pbuf.Call.FunctionMessageOrBuilder {
			public static final com.google.protobuf.Descriptors.Descriptor
					getDescriptor() {
				return com.pbuf.Call.internal_static_FunctionMessage_descriptor;
			}
			
			protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
					internalGetFieldAccessorTable() {
				return com.pbuf.Call.internal_static_FunctionMessage_fieldAccessorTable;
			}
			
			// Construct using com.pbuf.Call.FunctionMessage.newBuilder()
			private Builder() {
				maybeForceBuilderInitialization();
			}
			
			private Builder(BuilderParent parent) {
				super(parent);
				maybeForceBuilderInitialization();
			}
			
			private void maybeForceBuilderInitialization() {
				if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
					getParametersFieldBuilder();
				}
			}
			
			private static Builder create() {
				return new Builder();
			}
			
			public Builder clear() {
				super.clear();
				functionId_ = 0;
				bitField0_ = (bitField0_ & ~0x00000001);
				if (parametersBuilder_ == null) {
					parameters_ = java.util.Collections.emptyList();
					bitField0_ = (bitField0_ & ~0x00000002);
				} else {
					parametersBuilder_.clear();
				}
				return this;
			}
			
			public Builder clone() {
				return create().mergeFrom(buildPartial());
			}
			
			public com.google.protobuf.Descriptors.Descriptor
					getDescriptorForType() {
				return com.pbuf.Call.FunctionMessage.getDescriptor();
			}
			
			public com.pbuf.Call.FunctionMessage getDefaultInstanceForType() {
				return com.pbuf.Call.FunctionMessage.getDefaultInstance();
			}
			
			public com.pbuf.Call.FunctionMessage build() {
				com.pbuf.Call.FunctionMessage result = buildPartial();
				if (!result.isInitialized()) {
					throw newUninitializedMessageException(result);
				}
				return result;
			}
			
			private com.pbuf.Call.FunctionMessage buildParsed()
					throws com.google.protobuf.InvalidProtocolBufferException {
				com.pbuf.Call.FunctionMessage result = buildPartial();
				if (!result.isInitialized()) {
					throw newUninitializedMessageException(result)
							.asInvalidProtocolBufferException();
				}
				return result;
			}
			
			public com.pbuf.Call.FunctionMessage buildPartial() {
				com.pbuf.Call.FunctionMessage result =
						new com.pbuf.Call.FunctionMessage(this);
				int from_bitField0_ = bitField0_;
				int to_bitField0_ = 0;
				if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
					to_bitField0_ |= 0x00000001;
				}
				result.functionId_ = functionId_;
				if (parametersBuilder_ == null) {
					if (((bitField0_ & 0x00000002) == 0x00000002)) {
						parameters_ =
								java.util.Collections
										.unmodifiableList(parameters_);
						bitField0_ = (bitField0_ & ~0x00000002);
					}
					result.parameters_ = parameters_;
				} else {
					result.parameters_ = parametersBuilder_.build();
				}
				result.bitField0_ = to_bitField0_;
				onBuilt();
				return result;
			}
			
			public Builder mergeFrom(com.google.protobuf.Message other) {
				if (other instanceof com.pbuf.Call.FunctionMessage) {
					return mergeFrom((com.pbuf.Call.FunctionMessage) other);
				} else {
					super.mergeFrom(other);
					return this;
				}
			}
			
			public Builder mergeFrom(com.pbuf.Call.FunctionMessage other) {
				if (other == com.pbuf.Call.FunctionMessage.getDefaultInstance())
					return this;
				if (other.hasFunctionId()) {
					setFunctionId(other.getFunctionId());
				}
				if (parametersBuilder_ == null) {
					if (!other.parameters_.isEmpty()) {
						if (parameters_.isEmpty()) {
							parameters_ = other.parameters_;
							bitField0_ = (bitField0_ & ~0x00000002);
						} else {
							ensureParametersIsMutable();
							parameters_.addAll(other.parameters_);
						}
						onChanged();
					}
				} else {
					if (!other.parameters_.isEmpty()) {
						if (parametersBuilder_.isEmpty()) {
							parametersBuilder_.dispose();
							parametersBuilder_ = null;
							parameters_ = other.parameters_;
							bitField0_ = (bitField0_ & ~0x00000002);
							parametersBuilder_ =
									com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders
											? getParametersFieldBuilder()
											: null;
						} else {
							parametersBuilder_
									.addAllMessages(other.parameters_);
						}
					}
				}
				this.mergeUnknownFields(other.getUnknownFields());
				return this;
			}
			
			public final boolean isInitialized() {
				if (!hasFunctionId()) {
					
					return false;
				}
				for (int i = 0; i < getParametersCount(); i++) {
					if (!getParameters(i).isInitialized()) {
						
						return false;
					}
				}
				return true;
			}
			
			public
					Builder
					mergeFrom(
							com.google.protobuf.CodedInputStream input,
							com.google.protobuf.ExtensionRegistryLite extensionRegistry)
							throws java.io.IOException {
				com.google.protobuf.UnknownFieldSet.Builder unknownFields =
						com.google.protobuf.UnknownFieldSet.newBuilder(this
								.getUnknownFields());
				while (true) {
					int tag = input.readTag();
					switch (tag) {
					case 0:
						this.setUnknownFields(unknownFields.build());
						onChanged();
						return this;
					default: {
						if (!parseUnknownField(input, unknownFields,
								extensionRegistry, tag)) {
							this.setUnknownFields(unknownFields.build());
							onChanged();
							return this;
						}
						break;
					}
					case 8: {
						bitField0_ |= 0x00000001;
						functionId_ = input.readInt32();
						break;
					}
					case 18: {
						com.pbuf.Call.VariantMessage.Builder subBuilder =
								com.pbuf.Call.VariantMessage.newBuilder();
						input.readMessage(subBuilder, extensionRegistry);
						addParameters(subBuilder.buildPartial());
						break;
					}
					}
				}
			}
			
			private int bitField0_;
			
			// required int32 function_id = 1;
			private int functionId_;
			
			public boolean hasFunctionId() {
				return ((bitField0_ & 0x00000001) == 0x00000001);
			}
			
			public int getFunctionId() {
				return functionId_;
			}
			
			public Builder setFunctionId(int value) {
				bitField0_ |= 0x00000001;
				functionId_ = value;
				onChanged();
				return this;
			}
			
			public Builder clearFunctionId() {
				bitField0_ = (bitField0_ & ~0x00000001);
				functionId_ = 0;
				onChanged();
				return this;
			}
			
			// repeated .VariantMessage parameters = 2;
			private java.util.List<com.pbuf.Call.VariantMessage> parameters_ =
					java.util.Collections.emptyList();
			
			private void ensureParametersIsMutable() {
				if (!((bitField0_ & 0x00000002) == 0x00000002)) {
					parameters_ =
							new java.util.ArrayList<com.pbuf.Call.VariantMessage>(
									parameters_);
					bitField0_ |= 0x00000002;
				}
			}
			
			private com.google.protobuf.RepeatedFieldBuilder<com.pbuf.Call.VariantMessage, com.pbuf.Call.VariantMessage.Builder, com.pbuf.Call.VariantMessageOrBuilder> parametersBuilder_;
			
			public java.util.List<com.pbuf.Call.VariantMessage>
					getParametersList() {
				if (parametersBuilder_ == null) {
					return java.util.Collections.unmodifiableList(parameters_);
				} else {
					return parametersBuilder_.getMessageList();
				}
			}
			
			public int getParametersCount() {
				if (parametersBuilder_ == null) {
					return parameters_.size();
				} else {
					return parametersBuilder_.getCount();
				}
			}
			
			public com.pbuf.Call.VariantMessage getParameters(int index) {
				if (parametersBuilder_ == null) {
					return parameters_.get(index);
				} else {
					return parametersBuilder_.getMessage(index);
				}
			}
			
			public Builder setParameters(int index,
					com.pbuf.Call.VariantMessage value) {
				if (parametersBuilder_ == null) {
					if (value == null) {
						throw new NullPointerException();
					}
					ensureParametersIsMutable();
					parameters_.set(index, value);
					onChanged();
				} else {
					parametersBuilder_.setMessage(index, value);
				}
				return this;
			}
			
			public Builder setParameters(int index,
					com.pbuf.Call.VariantMessage.Builder builderForValue) {
				if (parametersBuilder_ == null) {
					ensureParametersIsMutable();
					parameters_.set(index, builderForValue.build());
					onChanged();
				} else {
					parametersBuilder_.setMessage(index,
							builderForValue.build());
				}
				return this;
			}
			
			public Builder addParameters(com.pbuf.Call.VariantMessage value) {
				if (parametersBuilder_ == null) {
					if (value == null) {
						throw new NullPointerException();
					}
					ensureParametersIsMutable();
					parameters_.add(value);
					onChanged();
				} else {
					parametersBuilder_.addMessage(value);
				}
				return this;
			}
			
			public Builder addParameters(int index,
					com.pbuf.Call.VariantMessage value) {
				if (parametersBuilder_ == null) {
					if (value == null) {
						throw new NullPointerException();
					}
					ensureParametersIsMutable();
					parameters_.add(index, value);
					onChanged();
				} else {
					parametersBuilder_.addMessage(index, value);
				}
				return this;
			}
			
			public Builder addParameters(
					com.pbuf.Call.VariantMessage.Builder builderForValue) {
				if (parametersBuilder_ == null) {
					ensureParametersIsMutable();
					parameters_.add(builderForValue.build());
					onChanged();
				} else {
					parametersBuilder_.addMessage(builderForValue.build());
				}
				return this;
			}
			
			public Builder addParameters(int index,
					com.pbuf.Call.VariantMessage.Builder builderForValue) {
				if (parametersBuilder_ == null) {
					ensureParametersIsMutable();
					parameters_.add(index, builderForValue.build());
					onChanged();
				} else {
					parametersBuilder_.addMessage(index,
							builderForValue.build());
				}
				return this;
			}
			
			public
					Builder
					addAllParameters(
							java.lang.Iterable<? extends com.pbuf.Call.VariantMessage> values) {
				if (parametersBuilder_ == null) {
					ensureParametersIsMutable();
					super.addAll(values, parameters_);
					onChanged();
				} else {
					parametersBuilder_.addAllMessages(values);
				}
				return this;
			}
			
			public Builder clearParameters() {
				if (parametersBuilder_ == null) {
					parameters_ = java.util.Collections.emptyList();
					bitField0_ = (bitField0_ & ~0x00000002);
					onChanged();
				} else {
					parametersBuilder_.clear();
				}
				return this;
			}
			
			public Builder removeParameters(int index) {
				if (parametersBuilder_ == null) {
					ensureParametersIsMutable();
					parameters_.remove(index);
					onChanged();
				} else {
					parametersBuilder_.remove(index);
				}
				return this;
			}
			
			public com.pbuf.Call.VariantMessage.Builder getParametersBuilder(
					int index) {
				return getParametersFieldBuilder().getBuilder(index);
			}
			
			public com.pbuf.Call.VariantMessageOrBuilder
					getParametersOrBuilder(int index) {
				if (parametersBuilder_ == null) {
					return parameters_.get(index);
				} else {
					return parametersBuilder_.getMessageOrBuilder(index);
				}
			}
			
			public
					java.util.List<? extends com.pbuf.Call.VariantMessageOrBuilder>
					getParametersOrBuilderList() {
				if (parametersBuilder_ != null) {
					return parametersBuilder_.getMessageOrBuilderList();
				} else {
					return java.util.Collections.unmodifiableList(parameters_);
				}
			}
			
			public com.pbuf.Call.VariantMessage.Builder addParametersBuilder() {
				return getParametersFieldBuilder().addBuilder(
						com.pbuf.Call.VariantMessage.getDefaultInstance());
			}
			
			public com.pbuf.Call.VariantMessage.Builder addParametersBuilder(
					int index) {
				return getParametersFieldBuilder().addBuilder(index,
						com.pbuf.Call.VariantMessage.getDefaultInstance());
			}
			
			public java.util.List<com.pbuf.Call.VariantMessage.Builder>
					getParametersBuilderList() {
				return getParametersFieldBuilder().getBuilderList();
			}
			
			private
					com.google.protobuf.RepeatedFieldBuilder<com.pbuf.Call.VariantMessage, com.pbuf.Call.VariantMessage.Builder, com.pbuf.Call.VariantMessageOrBuilder>
					getParametersFieldBuilder() {
				if (parametersBuilder_ == null) {
					parametersBuilder_ =
							new com.google.protobuf.RepeatedFieldBuilder<com.pbuf.Call.VariantMessage, com.pbuf.Call.VariantMessage.Builder, com.pbuf.Call.VariantMessageOrBuilder>(
									parameters_,
									((bitField0_ & 0x00000002) == 0x00000002),
									getParentForChildren(), isClean());
					parameters_ = null;
				}
				return parametersBuilder_;
			}
			
			// @@protoc_insertion_point(builder_scope:FunctionMessage)
		}
		
		static {
			defaultInstance = new FunctionMessage(true);
			defaultInstance.initFields();
		}
		
		// @@protoc_insertion_point(class_scope:FunctionMessage)
	}
	
	public interface VariantMessageOrBuilder extends
			com.google.protobuf.MessageOrBuilder {
		
		// required .VariantMessage.VariantType type = 1;
		boolean hasType();
		
		com.pbuf.Call.VariantMessage.VariantType getType();
		
		// optional bool bool_value = 2;
		boolean hasBoolValue();
		
		boolean getBoolValue();
		
		// optional int32 int_value = 3;
		boolean hasIntValue();
		
		int getIntValue();
		
		// optional double double_value = 4;
		boolean hasDoubleValue();
		
		double getDoubleValue();
		
		// optional string string_value = 5;
		boolean hasStringValue();
		
		String getStringValue();
		
		// repeated int32 cardinalities = 6;
		java.util.List<java.lang.Integer> getCardinalitiesList();
		
		int getCardinalitiesCount();
		
		int getCardinalities(int index);
		
		// repeated bytes bool_matrix = 7;
		java.util.List<com.google.protobuf.ByteString> getBoolMatrixList();
		
		int getBoolMatrixCount();
		
		com.google.protobuf.ByteString getBoolMatrix(int index);
		
		// repeated int32 int_matrix = 8;
		java.util.List<java.lang.Integer> getIntMatrixList();
		
		int getIntMatrixCount();
		
		int getIntMatrix(int index);
		
		// repeated double double_matrix = 9;
		java.util.List<java.lang.Double> getDoubleMatrixList();
		
		int getDoubleMatrixCount();
		
		double getDoubleMatrix(int index);
		
		// repeated string string_matrix = 10;
		java.util.List<String> getStringMatrixList();
		
		int getStringMatrixCount();
		
		String getStringMatrix(int index);
	}
	
	public static final class VariantMessage extends
			com.google.protobuf.GeneratedMessage implements
			VariantMessageOrBuilder {
		// Use VariantMessage.newBuilder() to construct.
		private VariantMessage(Builder builder) {
			super(builder);
		}
		
		private VariantMessage(boolean noInit) {
		}
		
		private static final VariantMessage defaultInstance;
		
		public static VariantMessage getDefaultInstance() {
			return defaultInstance;
		}
		
		public VariantMessage getDefaultInstanceForType() {
			return defaultInstance;
		}
		
		public static final com.google.protobuf.Descriptors.Descriptor
				getDescriptor() {
			return com.pbuf.Call.internal_static_VariantMessage_descriptor;
		}
		
		protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
				internalGetFieldAccessorTable() {
			return com.pbuf.Call.internal_static_VariantMessage_fieldAccessorTable;
		}
		
		public enum VariantType implements
				com.google.protobuf.ProtocolMessageEnum {
			VOID(0, 1), BOOL(1, 2), INT(2, 3), DOUBLE(3, 4), STRING(4, 5),
			BOOL_MATRIX(5, 6), INT_MATRIX(6, 7), DOUBLE_MATRIX(7, 8),
			STRING_MATRIX(8, 9), ;
			
			public static final int VOID_VALUE = 1;
			public static final int BOOL_VALUE = 2;
			public static final int INT_VALUE = 3;
			public static final int DOUBLE_VALUE = 4;
			public static final int STRING_VALUE = 5;
			public static final int BOOL_MATRIX_VALUE = 6;
			public static final int INT_MATRIX_VALUE = 7;
			public static final int DOUBLE_MATRIX_VALUE = 8;
			public static final int STRING_MATRIX_VALUE = 9;
			
			public final int getNumber() {
				return value;
			}
			
			public static VariantType valueOf(int value) {
				switch (value) {
				case 1:
					return VOID;
				case 2:
					return BOOL;
				case 3:
					return INT;
				case 4:
					return DOUBLE;
				case 5:
					return STRING;
				case 6:
					return BOOL_MATRIX;
				case 7:
					return INT_MATRIX;
				case 8:
					return DOUBLE_MATRIX;
				case 9:
					return STRING_MATRIX;
				default:
					return null;
				}
			}
			
			public static com.google.protobuf.Internal.EnumLiteMap<VariantType>
					internalGetValueMap() {
				return internalValueMap;
			}
			
			private static com.google.protobuf.Internal.EnumLiteMap<VariantType> internalValueMap =
					new com.google.protobuf.Internal.EnumLiteMap<VariantType>() {
						public VariantType findValueByNumber(int number) {
							return VariantType.valueOf(number);
						}
					};
			
			public final com.google.protobuf.Descriptors.EnumValueDescriptor
					getValueDescriptor() {
				return getDescriptor().getValues().get(index);
			}
			
			public final com.google.protobuf.Descriptors.EnumDescriptor
					getDescriptorForType() {
				return getDescriptor();
			}
			
			public static final com.google.protobuf.Descriptors.EnumDescriptor
					getDescriptor() {
				return com.pbuf.Call.VariantMessage.getDescriptor()
						.getEnumTypes().get(0);
			}
			
			private static final VariantType[] VALUES = { VOID, BOOL, INT,
					DOUBLE, STRING, BOOL_MATRIX, INT_MATRIX, DOUBLE_MATRIX,
					STRING_MATRIX, };
			
			public static VariantType valueOf(
					com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
				if (desc.getType() != getDescriptor()) {
					throw new java.lang.IllegalArgumentException(
							"EnumValueDescriptor is not for this type.");
				}
				return VALUES[desc.getIndex()];
			}
			
			private final int index;
			private final int value;
			
			private VariantType(int index, int value) {
				this.index = index;
				this.value = value;
			}
			
			// @@protoc_insertion_point(enum_scope:VariantMessage.VariantType)
		}
		
		private int bitField0_;
		// required .VariantMessage.VariantType type = 1;
		public static final int TYPE_FIELD_NUMBER = 1;
		private com.pbuf.Call.VariantMessage.VariantType type_;
		
		public boolean hasType() {
			return ((bitField0_ & 0x00000001) == 0x00000001);
		}
		
		public com.pbuf.Call.VariantMessage.VariantType getType() {
			return type_;
		}
		
		// optional bool bool_value = 2;
		public static final int BOOL_VALUE_FIELD_NUMBER = 2;
		private boolean boolValue_;
		
		public boolean hasBoolValue() {
			return ((bitField0_ & 0x00000002) == 0x00000002);
		}
		
		public boolean getBoolValue() {
			return boolValue_;
		}
		
		// optional int32 int_value = 3;
		public static final int INT_VALUE_FIELD_NUMBER = 3;
		private int intValue_;
		
		public boolean hasIntValue() {
			return ((bitField0_ & 0x00000004) == 0x00000004);
		}
		
		public int getIntValue() {
			return intValue_;
		}
		
		// optional double double_value = 4;
		public static final int DOUBLE_VALUE_FIELD_NUMBER = 4;
		private double doubleValue_;
		
		public boolean hasDoubleValue() {
			return ((bitField0_ & 0x00000008) == 0x00000008);
		}
		
		public double getDoubleValue() {
			return doubleValue_;
		}
		
		// optional string string_value = 5;
		public static final int STRING_VALUE_FIELD_NUMBER = 5;
		private Object stringValue_;
		
		public boolean hasStringValue() {
			return ((bitField0_ & 0x00000010) == 0x00000010);
		}
		
		public String getStringValue() {
			Object ref = stringValue_;
			if (ref instanceof String) {
				return (String) ref;
			} else {
				com.google.protobuf.ByteString bs =
						(com.google.protobuf.ByteString) ref;
				String s = bs.toStringUtf8();
				if (com.google.protobuf.Internal.isValidUtf8(bs)) {
					stringValue_ = s;
				}
				return s;
			}
		}
		
		private com.google.protobuf.ByteString getStringValueBytes() {
			Object ref = stringValue_;
			if (ref instanceof String) {
				com.google.protobuf.ByteString b =
						com.google.protobuf.ByteString
								.copyFromUtf8((String) ref);
				stringValue_ = b;
				return b;
			} else {
				return (com.google.protobuf.ByteString) ref;
			}
		}
		
		// repeated int32 cardinalities = 6;
		public static final int CARDINALITIES_FIELD_NUMBER = 6;
		private java.util.List<java.lang.Integer> cardinalities_;
		
		public java.util.List<java.lang.Integer> getCardinalitiesList() {
			return cardinalities_;
		}
		
		public int getCardinalitiesCount() {
			return cardinalities_.size();
		}
		
		public int getCardinalities(int index) {
			return cardinalities_.get(index);
		}
		
		// repeated bytes bool_matrix = 7;
		public static final int BOOL_MATRIX_FIELD_NUMBER = 7;
		private java.util.List<com.google.protobuf.ByteString> boolMatrix_;
		
		public java.util.List<com.google.protobuf.ByteString>
				getBoolMatrixList() {
			return boolMatrix_;
		}
		
		public int getBoolMatrixCount() {
			return boolMatrix_.size();
		}
		
		public com.google.protobuf.ByteString getBoolMatrix(int index) {
			return boolMatrix_.get(index);
		}
		
		// repeated int32 int_matrix = 8;
		public static final int INT_MATRIX_FIELD_NUMBER = 8;
		private java.util.List<java.lang.Integer> intMatrix_;
		
		public java.util.List<java.lang.Integer> getIntMatrixList() {
			return intMatrix_;
		}
		
		public int getIntMatrixCount() {
			return intMatrix_.size();
		}
		
		public int getIntMatrix(int index) {
			return intMatrix_.get(index);
		}
		
		// repeated double double_matrix = 9;
		public static final int DOUBLE_MATRIX_FIELD_NUMBER = 9;
		private java.util.List<java.lang.Double> doubleMatrix_;
		
		public java.util.List<java.lang.Double> getDoubleMatrixList() {
			return doubleMatrix_;
		}
		
		public int getDoubleMatrixCount() {
			return doubleMatrix_.size();
		}
		
		public double getDoubleMatrix(int index) {
			return doubleMatrix_.get(index);
		}
		
		// repeated string string_matrix = 10;
		public static final int STRING_MATRIX_FIELD_NUMBER = 10;
		private com.google.protobuf.LazyStringList stringMatrix_;
		
		public java.util.List<String> getStringMatrixList() {
			return stringMatrix_;
		}
		
		public int getStringMatrixCount() {
			return stringMatrix_.size();
		}
		
		public String getStringMatrix(int index) {
			return stringMatrix_.get(index);
		}
		
		private void initFields() {
			type_ = com.pbuf.Call.VariantMessage.VariantType.VOID;
			boolValue_ = false;
			intValue_ = 0;
			doubleValue_ = 0D;
			stringValue_ = "";
			cardinalities_ = java.util.Collections.emptyList();
			;
			boolMatrix_ = java.util.Collections.emptyList();
			;
			intMatrix_ = java.util.Collections.emptyList();
			;
			doubleMatrix_ = java.util.Collections.emptyList();
			;
			stringMatrix_ = com.google.protobuf.LazyStringArrayList.EMPTY;
		}
		
		private byte memoizedIsInitialized = -1;
		
		public final boolean isInitialized() {
			byte isInitialized = memoizedIsInitialized;
			if (isInitialized != -1)
				return isInitialized == 1;
			
			if (!hasType()) {
				memoizedIsInitialized = 0;
				return false;
			}
			memoizedIsInitialized = 1;
			return true;
		}
		
		public void writeTo(com.google.protobuf.CodedOutputStream output)
				throws java.io.IOException {
			getSerializedSize();
			if (((bitField0_ & 0x00000001) == 0x00000001)) {
				output.writeEnum(1, type_.getNumber());
			}
			if (((bitField0_ & 0x00000002) == 0x00000002)) {
				output.writeBool(2, boolValue_);
			}
			if (((bitField0_ & 0x00000004) == 0x00000004)) {
				output.writeInt32(3, intValue_);
			}
			if (((bitField0_ & 0x00000008) == 0x00000008)) {
				output.writeDouble(4, doubleValue_);
			}
			if (((bitField0_ & 0x00000010) == 0x00000010)) {
				output.writeBytes(5, getStringValueBytes());
			}
			for (int i = 0; i < cardinalities_.size(); i++) {
				output.writeInt32(6, cardinalities_.get(i));
			}
			for (int i = 0; i < boolMatrix_.size(); i++) {
				output.writeBytes(7, boolMatrix_.get(i));
			}
			for (int i = 0; i < intMatrix_.size(); i++) {
				output.writeInt32(8, intMatrix_.get(i));
			}
			for (int i = 0; i < doubleMatrix_.size(); i++) {
				output.writeDouble(9, doubleMatrix_.get(i));
			}
			for (int i = 0; i < stringMatrix_.size(); i++) {
				output.writeBytes(10, stringMatrix_.getByteString(i));
			}
			getUnknownFields().writeTo(output);
		}
		
		private int memoizedSerializedSize = -1;
		
		public int getSerializedSize() {
			int size = memoizedSerializedSize;
			if (size != -1)
				return size;
			
			size = 0;
			if (((bitField0_ & 0x00000001) == 0x00000001)) {
				size +=
						com.google.protobuf.CodedOutputStream.computeEnumSize(
								1, type_.getNumber());
			}
			if (((bitField0_ & 0x00000002) == 0x00000002)) {
				size +=
						com.google.protobuf.CodedOutputStream.computeBoolSize(
								2, boolValue_);
			}
			if (((bitField0_ & 0x00000004) == 0x00000004)) {
				size +=
						com.google.protobuf.CodedOutputStream.computeInt32Size(
								3, intValue_);
			}
			if (((bitField0_ & 0x00000008) == 0x00000008)) {
				size +=
						com.google.protobuf.CodedOutputStream
								.computeDoubleSize(4, doubleValue_);
			}
			if (((bitField0_ & 0x00000010) == 0x00000010)) {
				size +=
						com.google.protobuf.CodedOutputStream.computeBytesSize(
								5, getStringValueBytes());
			}
			{
				int dataSize = 0;
				for (int i = 0; i < cardinalities_.size(); i++) {
					dataSize +=
							com.google.protobuf.CodedOutputStream
									.computeInt32SizeNoTag(cardinalities_
											.get(i));
				}
				size += dataSize;
				size += 1 * getCardinalitiesList().size();
			}
			{
				int dataSize = 0;
				for (int i = 0; i < boolMatrix_.size(); i++) {
					dataSize +=
							com.google.protobuf.CodedOutputStream
									.computeBytesSizeNoTag(boolMatrix_.get(i));
				}
				size += dataSize;
				size += 1 * getBoolMatrixList().size();
			}
			{
				int dataSize = 0;
				for (int i = 0; i < intMatrix_.size(); i++) {
					dataSize +=
							com.google.protobuf.CodedOutputStream
									.computeInt32SizeNoTag(intMatrix_.get(i));
				}
				size += dataSize;
				size += 1 * getIntMatrixList().size();
			}
			{
				int dataSize = 0;
				dataSize = 8 * getDoubleMatrixList().size();
				size += dataSize;
				size += 1 * getDoubleMatrixList().size();
			}
			{
				int dataSize = 0;
				for (int i = 0; i < stringMatrix_.size(); i++) {
					dataSize +=
							com.google.protobuf.CodedOutputStream
									.computeBytesSizeNoTag(stringMatrix_
											.getByteString(i));
				}
				size += dataSize;
				size += 1 * getStringMatrixList().size();
			}
			size += getUnknownFields().getSerializedSize();
			memoizedSerializedSize = size;
			return size;
		}
		
		@java.lang.Override
		protected Object writeReplace() throws java.io.ObjectStreamException {
			return super.writeReplace();
		}
		
		public static com.pbuf.Call.VariantMessage parseFrom(
				com.google.protobuf.ByteString data)
				throws com.google.protobuf.InvalidProtocolBufferException {
			return newBuilder().mergeFrom(data).buildParsed();
		}
		
		public static com.pbuf.Call.VariantMessage parseFrom(
				com.google.protobuf.ByteString data,
				com.google.protobuf.ExtensionRegistryLite extensionRegistry)
				throws com.google.protobuf.InvalidProtocolBufferException {
			return newBuilder().mergeFrom(data, extensionRegistry)
					.buildParsed();
		}
		
		public static com.pbuf.Call.VariantMessage parseFrom(byte[] data)
				throws com.google.protobuf.InvalidProtocolBufferException {
			return newBuilder().mergeFrom(data).buildParsed();
		}
		
		public static com.pbuf.Call.VariantMessage parseFrom(byte[] data,
				com.google.protobuf.ExtensionRegistryLite extensionRegistry)
				throws com.google.protobuf.InvalidProtocolBufferException {
			return newBuilder().mergeFrom(data, extensionRegistry)
					.buildParsed();
		}
		
		public static com.pbuf.Call.VariantMessage parseFrom(
				java.io.InputStream input) throws java.io.IOException {
			return newBuilder().mergeFrom(input).buildParsed();
		}
		
		public static com.pbuf.Call.VariantMessage parseFrom(
				java.io.InputStream input,
				com.google.protobuf.ExtensionRegistryLite extensionRegistry)
				throws java.io.IOException {
			return newBuilder().mergeFrom(input, extensionRegistry)
					.buildParsed();
		}
		
		public static com.pbuf.Call.VariantMessage parseDelimitedFrom(
				java.io.InputStream input) throws java.io.IOException {
			Builder builder = newBuilder();
			if (builder.mergeDelimitedFrom(input)) {
				return builder.buildParsed();
			} else {
				return null;
			}
		}
		
		public static com.pbuf.Call.VariantMessage parseDelimitedFrom(
				java.io.InputStream input,
				com.google.protobuf.ExtensionRegistryLite extensionRegistry)
				throws java.io.IOException {
			Builder builder = newBuilder();
			if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
				return builder.buildParsed();
			} else {
				return null;
			}
		}
		
		public static com.pbuf.Call.VariantMessage parseFrom(
				com.google.protobuf.CodedInputStream input)
				throws java.io.IOException {
			return newBuilder().mergeFrom(input).buildParsed();
		}
		
		public static com.pbuf.Call.VariantMessage parseFrom(
				com.google.protobuf.CodedInputStream input,
				com.google.protobuf.ExtensionRegistryLite extensionRegistry)
				throws java.io.IOException {
			return newBuilder().mergeFrom(input, extensionRegistry)
					.buildParsed();
		}
		
		public static Builder newBuilder() {
			return Builder.create();
		}
		
		public Builder newBuilderForType() {
			return newBuilder();
		}
		
		public static Builder
				newBuilder(com.pbuf.Call.VariantMessage prototype) {
			return newBuilder().mergeFrom(prototype);
		}
		
		public Builder toBuilder() {
			return newBuilder(this);
		}
		
		@java.lang.Override
		protected Builder newBuilderForType(
				com.google.protobuf.GeneratedMessage.BuilderParent parent) {
			Builder builder = new Builder(parent);
			return builder;
		}
		
		public static final class Builder extends
				com.google.protobuf.GeneratedMessage.Builder<Builder> implements
				com.pbuf.Call.VariantMessageOrBuilder {
			public static final com.google.protobuf.Descriptors.Descriptor
					getDescriptor() {
				return com.pbuf.Call.internal_static_VariantMessage_descriptor;
			}
			
			protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
					internalGetFieldAccessorTable() {
				return com.pbuf.Call.internal_static_VariantMessage_fieldAccessorTable;
			}
			
			// Construct using com.pbuf.Call.VariantMessage.newBuilder()
			private Builder() {
				maybeForceBuilderInitialization();
			}
			
			private Builder(BuilderParent parent) {
				super(parent);
				maybeForceBuilderInitialization();
			}
			
			private void maybeForceBuilderInitialization() {
				if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
				}
			}
			
			private static Builder create() {
				return new Builder();
			}
			
			public Builder clear() {
				super.clear();
				type_ = com.pbuf.Call.VariantMessage.VariantType.VOID;
				bitField0_ = (bitField0_ & ~0x00000001);
				boolValue_ = false;
				bitField0_ = (bitField0_ & ~0x00000002);
				intValue_ = 0;
				bitField0_ = (bitField0_ & ~0x00000004);
				doubleValue_ = 0D;
				bitField0_ = (bitField0_ & ~0x00000008);
				stringValue_ = "";
				bitField0_ = (bitField0_ & ~0x00000010);
				cardinalities_ = java.util.Collections.emptyList();
				;
				bitField0_ = (bitField0_ & ~0x00000020);
				boolMatrix_ = java.util.Collections.emptyList();
				;
				bitField0_ = (bitField0_ & ~0x00000040);
				intMatrix_ = java.util.Collections.emptyList();
				;
				bitField0_ = (bitField0_ & ~0x00000080);
				doubleMatrix_ = java.util.Collections.emptyList();
				;
				bitField0_ = (bitField0_ & ~0x00000100);
				stringMatrix_ = com.google.protobuf.LazyStringArrayList.EMPTY;
				bitField0_ = (bitField0_ & ~0x00000200);
				return this;
			}
			
			public Builder clone() {
				return create().mergeFrom(buildPartial());
			}
			
			public com.google.protobuf.Descriptors.Descriptor
					getDescriptorForType() {
				return com.pbuf.Call.VariantMessage.getDescriptor();
			}
			
			public com.pbuf.Call.VariantMessage getDefaultInstanceForType() {
				return com.pbuf.Call.VariantMessage.getDefaultInstance();
			}
			
			public com.pbuf.Call.VariantMessage build() {
				com.pbuf.Call.VariantMessage result = buildPartial();
				if (!result.isInitialized()) {
					throw newUninitializedMessageException(result);
				}
				return result;
			}
			
			private com.pbuf.Call.VariantMessage buildParsed()
					throws com.google.protobuf.InvalidProtocolBufferException {
				com.pbuf.Call.VariantMessage result = buildPartial();
				if (!result.isInitialized()) {
					throw newUninitializedMessageException(result)
							.asInvalidProtocolBufferException();
				}
				return result;
			}
			
			public com.pbuf.Call.VariantMessage buildPartial() {
				com.pbuf.Call.VariantMessage result =
						new com.pbuf.Call.VariantMessage(this);
				int from_bitField0_ = bitField0_;
				int to_bitField0_ = 0;
				if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
					to_bitField0_ |= 0x00000001;
				}
				result.type_ = type_;
				if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
					to_bitField0_ |= 0x00000002;
				}
				result.boolValue_ = boolValue_;
				if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
					to_bitField0_ |= 0x00000004;
				}
				result.intValue_ = intValue_;
				if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
					to_bitField0_ |= 0x00000008;
				}
				result.doubleValue_ = doubleValue_;
				if (((from_bitField0_ & 0x00000010) == 0x00000010)) {
					to_bitField0_ |= 0x00000010;
				}
				result.stringValue_ = stringValue_;
				if (((bitField0_ & 0x00000020) == 0x00000020)) {
					cardinalities_ =
							java.util.Collections
									.unmodifiableList(cardinalities_);
					bitField0_ = (bitField0_ & ~0x00000020);
				}
				result.cardinalities_ = cardinalities_;
				if (((bitField0_ & 0x00000040) == 0x00000040)) {
					boolMatrix_ =
							java.util.Collections.unmodifiableList(boolMatrix_);
					bitField0_ = (bitField0_ & ~0x00000040);
				}
				result.boolMatrix_ = boolMatrix_;
				if (((bitField0_ & 0x00000080) == 0x00000080)) {
					intMatrix_ =
							java.util.Collections.unmodifiableList(intMatrix_);
					bitField0_ = (bitField0_ & ~0x00000080);
				}
				result.intMatrix_ = intMatrix_;
				if (((bitField0_ & 0x00000100) == 0x00000100)) {
					doubleMatrix_ =
							java.util.Collections
									.unmodifiableList(doubleMatrix_);
					bitField0_ = (bitField0_ & ~0x00000100);
				}
				result.doubleMatrix_ = doubleMatrix_;
				if (((bitField0_ & 0x00000200) == 0x00000200)) {
					stringMatrix_ =
							new com.google.protobuf.UnmodifiableLazyStringList(
									stringMatrix_);
					bitField0_ = (bitField0_ & ~0x00000200);
				}
				result.stringMatrix_ = stringMatrix_;
				result.bitField0_ = to_bitField0_;
				onBuilt();
				return result;
			}
			
			public Builder mergeFrom(com.google.protobuf.Message other) {
				if (other instanceof com.pbuf.Call.VariantMessage) {
					return mergeFrom((com.pbuf.Call.VariantMessage) other);
				} else {
					super.mergeFrom(other);
					return this;
				}
			}
			
			public Builder mergeFrom(com.pbuf.Call.VariantMessage other) {
				if (other == com.pbuf.Call.VariantMessage.getDefaultInstance())
					return this;
				if (other.hasType()) {
					setType(other.getType());
				}
				if (other.hasBoolValue()) {
					setBoolValue(other.getBoolValue());
				}
				if (other.hasIntValue()) {
					setIntValue(other.getIntValue());
				}
				if (other.hasDoubleValue()) {
					setDoubleValue(other.getDoubleValue());
				}
				if (other.hasStringValue()) {
					setStringValue(other.getStringValue());
				}
				if (!other.cardinalities_.isEmpty()) {
					if (cardinalities_.isEmpty()) {
						cardinalities_ = other.cardinalities_;
						bitField0_ = (bitField0_ & ~0x00000020);
					} else {
						ensureCardinalitiesIsMutable();
						cardinalities_.addAll(other.cardinalities_);
					}
					onChanged();
				}
				if (!other.boolMatrix_.isEmpty()) {
					if (boolMatrix_.isEmpty()) {
						boolMatrix_ = other.boolMatrix_;
						bitField0_ = (bitField0_ & ~0x00000040);
					} else {
						ensureBoolMatrixIsMutable();
						boolMatrix_.addAll(other.boolMatrix_);
					}
					onChanged();
				}
				if (!other.intMatrix_.isEmpty()) {
					if (intMatrix_.isEmpty()) {
						intMatrix_ = other.intMatrix_;
						bitField0_ = (bitField0_ & ~0x00000080);
					} else {
						ensureIntMatrixIsMutable();
						intMatrix_.addAll(other.intMatrix_);
					}
					onChanged();
				}
				if (!other.doubleMatrix_.isEmpty()) {
					if (doubleMatrix_.isEmpty()) {
						doubleMatrix_ = other.doubleMatrix_;
						bitField0_ = (bitField0_ & ~0x00000100);
					} else {
						ensureDoubleMatrixIsMutable();
						doubleMatrix_.addAll(other.doubleMatrix_);
					}
					onChanged();
				}
				if (!other.stringMatrix_.isEmpty()) {
					if (stringMatrix_.isEmpty()) {
						stringMatrix_ = other.stringMatrix_;
						bitField0_ = (bitField0_ & ~0x00000200);
					} else {
						ensureStringMatrixIsMutable();
						stringMatrix_.addAll(other.stringMatrix_);
					}
					onChanged();
				}
				this.mergeUnknownFields(other.getUnknownFields());
				return this;
			}
			
			public final boolean isInitialized() {
				if (!hasType()) {
					
					return false;
				}
				return true;
			}
			
			public
					Builder
					mergeFrom(
							com.google.protobuf.CodedInputStream input,
							com.google.protobuf.ExtensionRegistryLite extensionRegistry)
							throws java.io.IOException {
				com.google.protobuf.UnknownFieldSet.Builder unknownFields =
						com.google.protobuf.UnknownFieldSet.newBuilder(this
								.getUnknownFields());
				while (true) {
					int tag = input.readTag();
					switch (tag) {
					case 0:
						this.setUnknownFields(unknownFields.build());
						onChanged();
						return this;
					default: {
						if (!parseUnknownField(input, unknownFields,
								extensionRegistry, tag)) {
							this.setUnknownFields(unknownFields.build());
							onChanged();
							return this;
						}
						break;
					}
					case 8: {
						int rawValue = input.readEnum();
						com.pbuf.Call.VariantMessage.VariantType value =
								com.pbuf.Call.VariantMessage.VariantType
										.valueOf(rawValue);
						if (value == null) {
							unknownFields.mergeVarintField(1, rawValue);
						} else {
							bitField0_ |= 0x00000001;
							type_ = value;
						}
						break;
					}
					case 16: {
						bitField0_ |= 0x00000002;
						boolValue_ = input.readBool();
						break;
					}
					case 24: {
						bitField0_ |= 0x00000004;
						intValue_ = input.readInt32();
						break;
					}
					case 33: {
						bitField0_ |= 0x00000008;
						doubleValue_ = input.readDouble();
						break;
					}
					case 42: {
						bitField0_ |= 0x00000010;
						stringValue_ = input.readBytes();
						break;
					}
					case 48: {
						ensureCardinalitiesIsMutable();
						cardinalities_.add(input.readInt32());
						break;
					}
					case 50: {
						int length = input.readRawVarint32();
						int limit = input.pushLimit(length);
						while (input.getBytesUntilLimit() > 0) {
							addCardinalities(input.readInt32());
						}
						input.popLimit(limit);
						break;
					}
					case 58: {
						ensureBoolMatrixIsMutable();
						boolMatrix_.add(input.readBytes());
						break;
					}
					case 64: {
						ensureIntMatrixIsMutable();
						intMatrix_.add(input.readInt32());
						break;
					}
					case 66: {
						int length = input.readRawVarint32();
						int limit = input.pushLimit(length);
						while (input.getBytesUntilLimit() > 0) {
							addIntMatrix(input.readInt32());
						}
						input.popLimit(limit);
						break;
					}
					case 73: {
						ensureDoubleMatrixIsMutable();
						doubleMatrix_.add(input.readDouble());
						break;
					}
					case 74: {
						int length = input.readRawVarint32();
						int limit = input.pushLimit(length);
						while (input.getBytesUntilLimit() > 0) {
							addDoubleMatrix(input.readDouble());
						}
						input.popLimit(limit);
						break;
					}
					case 82: {
						ensureStringMatrixIsMutable();
						stringMatrix_.add(input.readBytes());
						break;
					}
					}
				}
			}
			
			private int bitField0_;
			
			// required .VariantMessage.VariantType type = 1;
			private com.pbuf.Call.VariantMessage.VariantType type_ =
					com.pbuf.Call.VariantMessage.VariantType.VOID;
			
			public boolean hasType() {
				return ((bitField0_ & 0x00000001) == 0x00000001);
			}
			
			public com.pbuf.Call.VariantMessage.VariantType getType() {
				return type_;
			}
			
			public Builder setType(
					com.pbuf.Call.VariantMessage.VariantType value) {
				if (value == null) {
					throw new NullPointerException();
				}
				bitField0_ |= 0x00000001;
				type_ = value;
				onChanged();
				return this;
			}
			
			public Builder clearType() {
				bitField0_ = (bitField0_ & ~0x00000001);
				type_ = com.pbuf.Call.VariantMessage.VariantType.VOID;
				onChanged();
				return this;
			}
			
			// optional bool bool_value = 2;
			private boolean boolValue_;
			
			public boolean hasBoolValue() {
				return ((bitField0_ & 0x00000002) == 0x00000002);
			}
			
			public boolean getBoolValue() {
				return boolValue_;
			}
			
			public Builder setBoolValue(boolean value) {
				bitField0_ |= 0x00000002;
				boolValue_ = value;
				onChanged();
				return this;
			}
			
			public Builder clearBoolValue() {
				bitField0_ = (bitField0_ & ~0x00000002);
				boolValue_ = false;
				onChanged();
				return this;
			}
			
			// optional int32 int_value = 3;
			private int intValue_;
			
			public boolean hasIntValue() {
				return ((bitField0_ & 0x00000004) == 0x00000004);
			}
			
			public int getIntValue() {
				return intValue_;
			}
			
			public Builder setIntValue(int value) {
				bitField0_ |= 0x00000004;
				intValue_ = value;
				onChanged();
				return this;
			}
			
			public Builder clearIntValue() {
				bitField0_ = (bitField0_ & ~0x00000004);
				intValue_ = 0;
				onChanged();
				return this;
			}
			
			// optional double double_value = 4;
			private double doubleValue_;
			
			public boolean hasDoubleValue() {
				return ((bitField0_ & 0x00000008) == 0x00000008);
			}
			
			public double getDoubleValue() {
				return doubleValue_;
			}
			
			public Builder setDoubleValue(double value) {
				bitField0_ |= 0x00000008;
				doubleValue_ = value;
				onChanged();
				return this;
			}
			
			public Builder clearDoubleValue() {
				bitField0_ = (bitField0_ & ~0x00000008);
				doubleValue_ = 0D;
				onChanged();
				return this;
			}
			
			// optional string string_value = 5;
			private Object stringValue_ = "";
			
			public boolean hasStringValue() {
				return ((bitField0_ & 0x00000010) == 0x00000010);
			}
			
			public String getStringValue() {
				Object ref = stringValue_;
				if (!(ref instanceof String)) {
					String s =
							((com.google.protobuf.ByteString) ref)
									.toStringUtf8();
					stringValue_ = s;
					return s;
				} else {
					return (String) ref;
				}
			}
			
			public Builder setStringValue(String value) {
				if (value == null) {
					throw new NullPointerException();
				}
				bitField0_ |= 0x00000010;
				stringValue_ = value;
				onChanged();
				return this;
			}
			
			public Builder clearStringValue() {
				bitField0_ = (bitField0_ & ~0x00000010);
				stringValue_ = getDefaultInstance().getStringValue();
				onChanged();
				return this;
			}
			
			void setStringValue(com.google.protobuf.ByteString value) {
				bitField0_ |= 0x00000010;
				stringValue_ = value;
				onChanged();
			}
			
			// repeated int32 cardinalities = 6;
			private java.util.List<java.lang.Integer> cardinalities_ =
					java.util.Collections.emptyList();;
			
			private void ensureCardinalitiesIsMutable() {
				if (!((bitField0_ & 0x00000020) == 0x00000020)) {
					cardinalities_ =
							new java.util.ArrayList<java.lang.Integer>(
									cardinalities_);
					bitField0_ |= 0x00000020;
				}
			}
			
			public java.util.List<java.lang.Integer> getCardinalitiesList() {
				return java.util.Collections.unmodifiableList(cardinalities_);
			}
			
			public int getCardinalitiesCount() {
				return cardinalities_.size();
			}
			
			public int getCardinalities(int index) {
				return cardinalities_.get(index);
			}
			
			public Builder setCardinalities(int index, int value) {
				ensureCardinalitiesIsMutable();
				cardinalities_.set(index, value);
				onChanged();
				return this;
			}
			
			public Builder addCardinalities(int value) {
				ensureCardinalitiesIsMutable();
				cardinalities_.add(value);
				onChanged();
				return this;
			}
			
			public Builder addAllCardinalities(
					java.lang.Iterable<? extends java.lang.Integer> values) {
				ensureCardinalitiesIsMutable();
				super.addAll(values, cardinalities_);
				onChanged();
				return this;
			}
			
			public Builder clearCardinalities() {
				cardinalities_ = java.util.Collections.emptyList();
				;
				bitField0_ = (bitField0_ & ~0x00000020);
				onChanged();
				return this;
			}
			
			// repeated bytes bool_matrix = 7;
			private java.util.List<com.google.protobuf.ByteString> boolMatrix_ =
					java.util.Collections.emptyList();;
			
			private void ensureBoolMatrixIsMutable() {
				if (!((bitField0_ & 0x00000040) == 0x00000040)) {
					boolMatrix_ =
							new java.util.ArrayList<com.google.protobuf.ByteString>(
									boolMatrix_);
					bitField0_ |= 0x00000040;
				}
			}
			
			public java.util.List<com.google.protobuf.ByteString>
					getBoolMatrixList() {
				return java.util.Collections.unmodifiableList(boolMatrix_);
			}
			
			public int getBoolMatrixCount() {
				return boolMatrix_.size();
			}
			
			public com.google.protobuf.ByteString getBoolMatrix(int index) {
				return boolMatrix_.get(index);
			}
			
			public Builder setBoolMatrix(int index,
					com.google.protobuf.ByteString value) {
				if (value == null) {
					throw new NullPointerException();
				}
				ensureBoolMatrixIsMutable();
				boolMatrix_.set(index, value);
				onChanged();
				return this;
			}
			
			public Builder addBoolMatrix(com.google.protobuf.ByteString value) {
				if (value == null) {
					throw new NullPointerException();
				}
				ensureBoolMatrixIsMutable();
				boolMatrix_.add(value);
				onChanged();
				return this;
			}
			
			public
					Builder
					addAllBoolMatrix(
							java.lang.Iterable<? extends com.google.protobuf.ByteString> values) {
				ensureBoolMatrixIsMutable();
				super.addAll(values, boolMatrix_);
				onChanged();
				return this;
			}
			
			public Builder clearBoolMatrix() {
				boolMatrix_ = java.util.Collections.emptyList();
				;
				bitField0_ = (bitField0_ & ~0x00000040);
				onChanged();
				return this;
			}
			
			// repeated int32 int_matrix = 8;
			private java.util.List<java.lang.Integer> intMatrix_ =
					java.util.Collections.emptyList();;
			
			private void ensureIntMatrixIsMutable() {
				if (!((bitField0_ & 0x00000080) == 0x00000080)) {
					intMatrix_ =
							new java.util.ArrayList<java.lang.Integer>(
									intMatrix_);
					bitField0_ |= 0x00000080;
				}
			}
			
			public java.util.List<java.lang.Integer> getIntMatrixList() {
				return java.util.Collections.unmodifiableList(intMatrix_);
			}
			
			public int getIntMatrixCount() {
				return intMatrix_.size();
			}
			
			public int getIntMatrix(int index) {
				return intMatrix_.get(index);
			}
			
			public Builder setIntMatrix(int index, int value) {
				ensureIntMatrixIsMutable();
				intMatrix_.set(index, value);
				onChanged();
				return this;
			}
			
			public Builder addIntMatrix(int value) {
				ensureIntMatrixIsMutable();
				intMatrix_.add(value);
				onChanged();
				return this;
			}
			
			public Builder addAllIntMatrix(
					java.lang.Iterable<? extends java.lang.Integer> values) {
				ensureIntMatrixIsMutable();
				super.addAll(values, intMatrix_);
				onChanged();
				return this;
			}
			
			public Builder clearIntMatrix() {
				intMatrix_ = java.util.Collections.emptyList();
				;
				bitField0_ = (bitField0_ & ~0x00000080);
				onChanged();
				return this;
			}
			
			// repeated double double_matrix = 9;
			private java.util.List<java.lang.Double> doubleMatrix_ =
					java.util.Collections.emptyList();;
			
			private void ensureDoubleMatrixIsMutable() {
				if (!((bitField0_ & 0x00000100) == 0x00000100)) {
					doubleMatrix_ =
							new java.util.ArrayList<java.lang.Double>(
									doubleMatrix_);
					bitField0_ |= 0x00000100;
				}
			}
			
			public java.util.List<java.lang.Double> getDoubleMatrixList() {
				return java.util.Collections.unmodifiableList(doubleMatrix_);
			}
			
			public int getDoubleMatrixCount() {
				return doubleMatrix_.size();
			}
			
			public double getDoubleMatrix(int index) {
				return doubleMatrix_.get(index);
			}
			
			public Builder setDoubleMatrix(int index, double value) {
				ensureDoubleMatrixIsMutable();
				doubleMatrix_.set(index, value);
				onChanged();
				return this;
			}
			
			public Builder addDoubleMatrix(double value) {
				ensureDoubleMatrixIsMutable();
				doubleMatrix_.add(value);
				onChanged();
				return this;
			}
			
			public Builder addAllDoubleMatrix(
					java.lang.Iterable<? extends java.lang.Double> values) {
				ensureDoubleMatrixIsMutable();
				super.addAll(values, doubleMatrix_);
				onChanged();
				return this;
			}
			
			public Builder clearDoubleMatrix() {
				doubleMatrix_ = java.util.Collections.emptyList();
				;
				bitField0_ = (bitField0_ & ~0x00000100);
				onChanged();
				return this;
			}
			
			// repeated string string_matrix = 10;
			private com.google.protobuf.LazyStringList stringMatrix_ =
					com.google.protobuf.LazyStringArrayList.EMPTY;
			
			private void ensureStringMatrixIsMutable() {
				if (!((bitField0_ & 0x00000200) == 0x00000200)) {
					stringMatrix_ =
							new com.google.protobuf.LazyStringArrayList(
									stringMatrix_);
					bitField0_ |= 0x00000200;
				}
			}
			
			public java.util.List<String> getStringMatrixList() {
				return java.util.Collections.unmodifiableList(stringMatrix_);
			}
			
			public int getStringMatrixCount() {
				return stringMatrix_.size();
			}
			
			public String getStringMatrix(int index) {
				return stringMatrix_.get(index);
			}
			
			public Builder setStringMatrix(int index, String value) {
				if (value == null) {
					throw new NullPointerException();
				}
				ensureStringMatrixIsMutable();
				stringMatrix_.set(index, value);
				onChanged();
				return this;
			}
			
			public Builder addStringMatrix(String value) {
				if (value == null) {
					throw new NullPointerException();
				}
				ensureStringMatrixIsMutable();
				stringMatrix_.add(value);
				onChanged();
				return this;
			}
			
			public Builder
					addAllStringMatrix(java.lang.Iterable<String> values) {
				ensureStringMatrixIsMutable();
				super.addAll(values, stringMatrix_);
				onChanged();
				return this;
			}
			
			public Builder clearStringMatrix() {
				stringMatrix_ = com.google.protobuf.LazyStringArrayList.EMPTY;
				bitField0_ = (bitField0_ & ~0x00000200);
				onChanged();
				return this;
			}
			
			void addStringMatrix(com.google.protobuf.ByteString value) {
				ensureStringMatrixIsMutable();
				stringMatrix_.add(value);
				onChanged();
			}
			
			// @@protoc_insertion_point(builder_scope:VariantMessage)
		}
		
		static {
			defaultInstance = new VariantMessage(true);
			defaultInstance.initFields();
		}
		
		// @@protoc_insertion_point(class_scope:VariantMessage)
	}
	
	private static com.google.protobuf.Descriptors.Descriptor internal_static_FunctionMessage_descriptor;
	private static com.google.protobuf.GeneratedMessage.FieldAccessorTable internal_static_FunctionMessage_fieldAccessorTable;
	private static com.google.protobuf.Descriptors.Descriptor internal_static_VariantMessage_descriptor;
	private static com.google.protobuf.GeneratedMessage.FieldAccessorTable internal_static_VariantMessage_fieldAccessorTable;
	
	public static com.google.protobuf.Descriptors.FileDescriptor
			getDescriptor() {
		return descriptor;
	}
	
	private static com.google.protobuf.Descriptors.FileDescriptor descriptor;
	static {
		java.lang.String[] descriptorData =
				{
						"\n\035resources/protobuf/call.proto\"K\n\017Funct"
								+ "ionMessage\022\023\n\013function_id\030\001 \002(\005\022#\n\nparam"
								+ "eters\030\002 \003(\0132\017.VariantMessage\"\210\003\n\016Variant"
								+ "Message\022)\n\004type\030\001 \002(\0162\033.VariantMessage.V"
								+ "ariantType\022\022\n\nbool_value\030\002 \001(\010\022\021\n\tint_va"
								+ "lue\030\003 \001(\005\022\024\n\014double_value\030\004 \001(\001\022\024\n\014strin"
								+ "g_value\030\005 \001(\t\022\025\n\rcardinalities\030\006 \003(\005\022\023\n\013"
								+ "bool_matrix\030\007 \003(\014\022\022\n\nint_matrix\030\010 \003(\005\022\025\n"
								+ "\rdouble_matrix\030\t \003(\001\022\025\n\rstring_matrix\030\n "
								+ "\003(\t\"\211\001\n\013VariantType\022\010\n\004VOID\020\001\022\010\n\004BOOL\020\002\022",
						"\007\n\003INT\020\003\022\n\n\006DOUBLE\020\004\022\n\n\006STRING\020\005\022\017\n\013BOOL"
								+ "_MATRIX\020\006\022\016\n\nINT_MATRIX\020\007\022\021\n\rDOUBLE_MATR"
								+ "IX\020\010\022\021\n\rSTRING_MATRIX\020\tB\n\n\010com.pbuf" };
		com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
				new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
					public
							com.google.protobuf.ExtensionRegistry
							assignDescriptors(
									com.google.protobuf.Descriptors.FileDescriptor root) {
						descriptor = root;
						internal_static_FunctionMessage_descriptor =
								getDescriptor().getMessageTypes().get(0);
						internal_static_FunctionMessage_fieldAccessorTable =
								new com.google.protobuf.GeneratedMessage.FieldAccessorTable(
										internal_static_FunctionMessage_descriptor,
										new java.lang.String[] { "FunctionId",
												"Parameters", },
										com.pbuf.Call.FunctionMessage.class,
										com.pbuf.Call.FunctionMessage.Builder.class);
						internal_static_VariantMessage_descriptor =
								getDescriptor().getMessageTypes().get(1);
						internal_static_VariantMessage_fieldAccessorTable =
								new com.google.protobuf.GeneratedMessage.FieldAccessorTable(
										internal_static_VariantMessage_descriptor,
										new java.lang.String[] { "Type",
												"BoolValue", "IntValue",
												"DoubleValue", "StringValue",
												"Cardinalities", "BoolMatrix",
												"IntMatrix", "DoubleMatrix",
												"StringMatrix", },
										com.pbuf.Call.VariantMessage.class,
										com.pbuf.Call.VariantMessage.Builder.class);
						return null;
					}
				};
		com.google.protobuf.Descriptors.FileDescriptor
				.internalBuildGeneratedFileFrom(
						descriptorData,
						new com.google.protobuf.Descriptors.FileDescriptor[] {},
						assigner);
	}
	
	// @@protoc_insertion_point(outer_class_scope)
}
